### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by marvin521** [waps101/3DMM_edges#1]
```
'Error in abModelFittingCMU (line 7)
[tri,pts]=plyread('C:\Users\Dell\Documents\MATLAB\faces\00001_20061015_00418_neutral_face05.ply','tri');'
```

hi, anilbas
where should go to find this file? which database?

**Comment by waps101** [comment]
Please clone the latest version and try the demo.m script. This will execute the basic algorithm. Follow instructions in the readme to ensure you have the necessary supporting files.
