### ISSUE TITLE
ZR2BFM.m file is missing

### ISSUE THREAD

**Issue by ManS** [waps101/3DMM_edges#3]
I can't find this file in the repository. I need to get the correspondence between the detected landmarks and the BFM vertices. 

The only thing that I can find in the demo.m file is the (landmarks) array which contains 53 vertex indices, but I have no idea how I can map those to the 68 landmarks. 

Thanks!

**Comment by anilbas** [comment]
ZR2BFM.m and some other functions are updated now. 
Please clone the latest version and you should be able to run the code.
