### ISSUE TITLE
evaluation.m

### ISSUE THREAD

**Issue by adhereyuyu** [waps101/3DMM_edges#4]
Hi, I didn't find evaluation.m?

**Comment by xuhw16** [comment]
In occludingBoundaryVertices.m file,the last statement                                                          
              occludingVertices = intersect(occludingVertices,visiblevertices(FV, eye(3)));                                     why the transform maxtrix is eye(3)  rather than R which was caculated in program above.

**Comment by elliotresearcher** [comment]
same problem here,you found file or not?

**Comment by elliotresearcher** [comment]
it also gives an error at end 
Error using flipud (line 19)
X must be a 2-D matrix.

can you please guide me about this error
thanks

**Comment by waps101** [comment]
For now, demo.m provides a run through of the whole pipeline. We will add an evaluation script some time in the future which also shows how to run some evaluations.

**Comment by FUHUACANGYUE** [comment]
@waps101  Can you share the evaluation script now? Thanks!
