### ISSUE TITLE
occludingBoundaryVertices.m file

### ISSUE THREAD

**Issue by xuhw16** [waps101/3DMM_edges#6]
Thanks for your code. I want to ask about In occludingBoundaryVertices.m file, the last statement
occludingVertices = intersect(occludingVertices,visiblevertices(FV, eye(3)));                                                                           why the transform maxtrix is eye(3) rather than R which was caculated in program above.

**Comment by waps101** [comment]
The reason is because on line 12, the rotation matrix (if supplied) has already been applied to the vertices. So, the call to visiblevertices doesn't need to pass the rotation matrix to be applied again.
