### ISSUE TITLE
Distance between face and camera

### ISSUE THREAD

**Issue by Adra8373** [waps101/3DMM_edges#7]
Hi

I have a question when I used frames that have face close to the camera the fitting process is failed. that means the generated 3D model is not same as the 2D frame, could you explain to me why that happens, please?

**Comment by elliotresearcher** [comment]
it also gives an error at end 
Error using flipud (line 19)
X must be a 2-D matrix.

can you please guide me about this error
thanks

**Comment by Adra8373** [comment]
is this error in demo.m ?? I could not find flipud in demo?

**Comment by waps101** [comment]
Does the landmark detector successfully detect landmarks? If not, then the subsequent fitting definitely won't work. If it does detect landmarks you might get a bad result because of large perspective distortion which is not modelled by the orthographic camera used in our code.
