### ISSUE TITLE
X must be a 2-D matrix.

### ISSUE THREAD

**Issue by elliotresearcher** [waps101/3DMM_edges#8]
it also gives an error at end 
Error using flipud (line 19)
X must be a 2-D matrix.

can you please guide me about this error
thanks

**Comment by waps101** [comment]
I think you must be using an old version of matlab that does not support flipud being applied to 3D arrays (i.e. colour images). You could replace the line in render_face_FV.m that says:

im = flipud(im);

with:

im = im(end:1,:,:);
